apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbsrv
  labels:
    app: dbsrv
spec:
  selector:
    matchLabels:
      app: dbsrv
  replicas: 1
  template:
    metadata:
      labels:
        app: dbsrv
    spec:
      containers:
        - name: dbsrv
          image: snoman1/dbimg:V1
          args:
            - "--ignore-db-dir=lost+found"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
          ports:
            - name: db-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: db-password
      nodeSelector:
        # This is to make sure that depolyment should be created in same zone where EBS is created .
        #Make sure to create a label for this zone
        zone: us-east-1a
      volumes:
        - name: db-data
          # This AWS EBS volume must already exist.
          # This EBS Volume should exist in us-east-1a zone
          awsElasticBlockStore:
            volumeID: <VOLUMEID>
            fsType: ext4
